"""Singleton absorptions accepted after review (stage 2)."""

SINGLETON_MERGES = {
    'AI Agent Design': 'AI Agent',
    'AI Ideation': 'Ideation',
    'AI Image Generation': 'Image Generation',
    'AI Interaction Design': 'Interaction Design',
    'AI Learnability': 'Learnability',
    'AI Limitations and Realistic Expectations': 'AI Limitations',
    'AI Onboarding and Guidance': 'Onboarding',
    'AI Product Design Considerations': 'AI Product Design',
    'AI Product Design Patterns': 'AI Product Design',
    'AI Prompt Engineering': 'Prompt Engineering',
    'AI User Behavior': 'User Behavior',
    'AI User Interface Design': 'User Interface',
    'AI Workshop Facilitation': 'Workshop Facilitation',
    'AI and Research Operations': 'Research Operations',
    'AI in UX Research': 'AI in User Research',
    'AI-Assisted Ideation': 'Ideation',
    'Accessibility Research': 'Accessibility',
    'Accessibility in Testing': 'Accessibility',
    'Aesthetic Usability Effect': 'Aesthetic-Usability Effect',
    'Affordance in Design': 'Affordance',
    'Agile Design Process': 'Design Process',
    'Analytics Framework': 'Analytics',
    'Analytics Strategy': 'Analytics',
    'Analytics and Prioritization': 'Prioritization',
    'Analytics and Strategy': 'Analytics',
    'Animation Design': 'Animation',
    'Animation Timing': 'Animation',
    'Animation Usability': 'Animation',
    'Animation in UX': 'Animation',
    'Asynchronous Ideation': 'Ideation',
    'Augmented Reality Calibration': 'Augmented Reality',
    'Augmented Reality Onboarding': 'Augmented Reality',
    'Authentication Design': 'Authentication',
    'Behavioral Analytics': 'Analytics',
    "Children's UX Design": 'Young Users',
    'Cognitive Bias in Design': 'Cognitive Bias',
    'Color and Typography': 'Typography',
    'Compensatory Decision Making': 'Decision Making',
    'Conversion Funnel': 'Funnel',
    'Customer Journey Management': 'Customer Journey',
    'Customer Journey Visualization': 'Customer Journey',
    'Customer Service Information Architecture': 'Information Architecture',
    'Data Privacy': 'Privacy',
    'Data Storytelling': 'Storytelling',
    'Data-Driven Decision Making': 'Data-Driven Decision',
    'Democratic Decision-Making': 'Decision Making',
    'Design Benchmarking': 'Benchmarking',
    'Design Critique Process': 'Design Critique',
    'Design Ideation': 'Ideation',
    'Design Patterns for AI': 'Design Patterns',
    'Design System Operations': 'Design System',
    'Design Thinking and Shortcuts': 'Design Thinking',
    'DesignOps Maturity': 'DesignOps',
    'Diary Study Design': 'Study Design',
    'E-Commerce Design': 'E-Commerce',
    'Empathy Map': 'Empathy',
    'Empathy Mapping': 'Empathy',
    'Empathy in Design': 'Empathy',
    'Empty State Design': 'Empty State',
    'Eye-Tracking Studies': 'Eye Tracking',
    'Feature Discoverability': 'Discoverability',
    'Foldable Device Design': 'Device Design',
    'Form Design and Usability': 'Form Design',
    'Generative AI vs Search': 'Generative AI',
    'Ideation Methods': 'Ideation',
    'Image Accessibility': 'Accessibility',
    'Information Architecture for AI': 'Information Architecture',
    'Information Seeking Behavior': 'Information Seeking',
    'Information-Seeking Behavior': 'Information Seeking',
    'Integrated User Experience': 'User Experience',
    'Interaction Design Fundamentals': 'Interaction Design',
    'Interaction Design Optimization': 'Interaction Design',
    'Interface Customization': 'Customization',
    'Interface Patterns for Productivity': 'Productivity',
    'IoT and Smart Devices': 'Smart Devices',
    'Mobile Accessibility': 'Accessibility',
    'Mobile Form Design': 'Form Design',
    'Mobile Multitasking': 'Multitasking',
    'Mobile User Behavior': 'User Behavior',
    'Multitasking on Mobile': 'Multitasking',
    'Onboarding Patterns': 'Onboarding',
    'Onboarding and Learning': 'Onboarding',
    'Onboarding to AI': 'Onboarding',
    'Paper Prototyping': 'Prototyping',
    'Portfolio Development': 'Portfolio',
    'Prioritization Matrices': 'Prioritization',
    'Prioritization Methods': 'Prioritization',
    'Privacy Design': 'Privacy',
    'Privacy and AI Systems': 'Privacy',
    'Privacy and Security': 'Privacy',
    'Prompt Iteration': 'Prompt Engineering',
    'Qualitative Research Analysis': 'Qualitative Research',
    'Quantitative UX Research': 'Quantitative Research',
    'Quantitative Usability Testing': 'Usability Testing',
    'Quantitative and Qualitative Research': 'Qualitative Research',
    'Remote Usability Testing': 'Usability Testing',
    'Research Documentation': 'Documentation',
    'Research Participant Recruitment': 'Participant Recruitment',
    'Roadmapping Process': 'Roadmapping',
    'Search Analytics': 'Analytics',
    'Search User Experience': 'Search',
    'Service Design Evolution': 'Service Design',
    'Shared Device Design': 'Device Design',
    'Storytelling in Design': 'Storytelling',
    'Storytelling in Interviews': 'Storytelling',
    'Synchronous Ideation': 'Ideation',
    'Task Automation': 'Automation',
    'Team Collaboration with AI': 'Team Collaboration',
    'Team Decision-Making': 'Decision Making',
    'Trust and Privacy': 'Privacy',
    'Typography Terminology': 'Typography',
    'UX Audit Methods': 'UX Audit',
    'UX Benchmarking': 'Benchmarking',
    'UX Career Paths': 'UX Career',
    'UX Career Stages': 'UX Career',
    'UX Design for AI': 'AI in Design',
    'UX Documentation': 'Documentation',
    'UX Maturity and Strategy': 'UX Maturity',
    'UX Project Management': 'Project Management',
    'UX Research Practices': 'UX Research',
    'Usability Testing Bias': 'Usability Testing',
    'Usability Testing Methods': 'Usability Testing',
    'Usability Testing Tools': 'Usability Testing',
    'User Authentication': 'Authentication',
    'User Behavior Change': 'User Behavior',
    'User Experience Analysis': 'User Experience',
    'User Experience Definition': 'User Experience',
    'User Experience Degradation': 'User Experience',
    'User Experience Design': 'User Experience',
    'User Experience Metrics': 'UX Metrics',
    'User Experience Strategy': 'UX Strategy',
    'User Interface Quality': 'User Interface',
    'User Preferences and Customization': 'Customization',
    'User Privacy': 'Privacy',
    'User Research Infrastructure': 'User Research',
    'User Research Platforms': 'User Research',
    'User Trust and AI': 'User Trust',
    'User Types in Complex Applications': 'Complex Applications',
    'User Value Proposition': 'Value Proposition',
    'User-Centered Design Process': 'User-Centered Design',
    'Ux Design Process': 'Design Process',
    'Visual Affordance': 'Affordance',
    'Visual Design Glossary': 'Visual Design',
    'Visual Design Impact': 'Visual Design',
    'Visual Design Systems': 'Visual Design',
    'Web Accessibility': 'Accessibility',
    'Web Design Trends': 'Design Trends',
    'Website Information Architecture': 'Information Architecture',
}
