"""Generate wiki/orphans.md: the single-source concepts that have no page.

Stage 2 only creates a concept page from two sources up, so ~845 candidate
names cited by exactly one record never got one. That is deliberate (a page
compiling one source would just restate the record), but it left those names
as dead ends: a wikilink pointing nowhere.

This index removes the dead end without writing 845 pages. Each name resolves
to the one record that carries it. Generated, never hand-edited.
"""

import collections
import glob
import os
import re

import yaml

EPISODES_DIR = "wiki/episodes"
CONCEPTS_DIR = "wiki/concepts"
OUT = "wiki/orphans.md"
TODAY = os.environ.get("WIKI_DATE") or __import__("datetime").date.today().isoformat()

FM_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


def parse(path):
    content = open(path, encoding="utf-8").read()
    m = FM_RE.match(content)
    return (yaml.safe_load(m.group(1)), content[m.end():]) if m else (None, content)


def main():
    known = set()
    for path in glob.glob(f"{CONCEPTS_DIR}/*.md"):
        meta, _ = parse(path)
        if not meta:
            continue
        known.add(str(meta.get("name", "")).lower())
        for alias in meta.get("aliases") or []:
            known.add(str(alias).lower())

    where = collections.defaultdict(list)
    for path in glob.glob(f"{EPISODES_DIR}/*.md"):
        meta, _ = parse(path)
        if not meta or meta.get("type") != "source":
            continue
        base = os.path.splitext(os.path.basename(path))[0]
        for name in meta.get("concepts") or []:
            if str(name).lower() not in known:
                where[str(name)].append(base)

    orphans = {n: sorted(set(r)) for n, r in where.items() if len(set(r)) == 1}

    lines = [
        "---", "type: orphan-index", f"updated: {TODAY}", "---", "",
        "# Single-source concepts", "",
        "Generated by `stage3/orphan_index.py`. These names are cited by exactly",
        "one record each and have no concept page: one source cannot be compiled",
        "across sources, so stage 2 leaves them alone (docs/adr/0003). They are",
        "often the narrowest and most actionable ideas in the corpus, so this",
        "index makes them reachable. Open the record, not a concept page.", "",
        f"## Index ({len(orphans)})", "",
    ]
    for name in sorted(orphans, key=str.lower):
        lines.append(f"- **{name}** : [[{orphans[name][0]}]]")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"orphans: {len(orphans)} single-source concepts indexed -> {OUT}")


if __name__ == "__main__":
    main()
